### ISSUE TITLE
Implement propagators

### ISSUE THREAD

**Issue by bshi** [GoogleCloudPlatform/opentelemetry-operations-go#110]
Presently, trace context via HTTP header `X-Cloud-Trace-Context` (or the equivalent gRPC header) doesn't appear to be extracted from inbound requests.

OpenCensus equivalent: https://pkg.go.dev/go.opencensus.io/exporter/stackdriver/propagation

https://pkg.go.dev/go.opentelemetry.io/otel/propagators

**Comment by glassonion1** [comment]
I thought i needed too.
However, I thought that it should be implemented in open [telemetry-go-contrib](https://github.com/open-telemetry/opentelemetry-go-contrib) instead of exporter.

I tried implementing http propagator in my library below.
https://github.com/glassonion1/logz/blob/main/internal/propagation/http_format.go

**Comment by punya** [comment]
Related to #116.

**Comment by punya** [comment]
Related to https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/254 -- we should make sure we comply with the v2 spec.

**Comment by amammay** [comment]
just so i can have some ease of re-use in some of my own projects i went ahead and created a package based off @glassonion1 implementation with just some slight tweaks to work with open telemetry v0.20.0

https://github.com/amammay/propagationgcp
