### ISSUE TITLE
The new github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace will be impossible to be used in otel-collector

### ISSUE THREAD

**Issue by bogdandrutu** [GoogleCloudPlatform/opentelemetry-operations-go#181]
Right now after the upgrade to 1.0.0-RC1 this library requires `sdktrace.ReadOnlySpan` to be passed to the exporter, which otel-collector will not be able to produce since `sdktrace.ReadOnlySpan` are private interface (has a private method).

This is very urgent since it blocks the otel-collector release see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4146

**Comment by 0xc0d** [comment]
It is already implement in main branch, contributers are still working on a few missing features and bugs before releasing a new tag.

**Comment by punya** [comment]
@0xc0d IIUC, Bogdan filed this based on the unreleased code in the main branch, which will accept ReadOnlySnapshots instead of SpanSnapshot. The problem is that the GCP exporter in collector-contrib used to create new instances of SpanSnapshot, but it has no way to create new instances of ReadOnlySnapshot.

I have tried to resolve this by making our own notion of ReadOnlySnapshot which is a sub-interface of sdktrace.ReadOnlySnapshot but with no unexported funcs. Thus the exporter will be able to implement this interface.

**Comment by punya** [comment]
Reopening because I missed some APIs that needed to be migrated/forked.
