### ISSUE TITLE
propagator not mentioned or used

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/opentelemetry-operations-go#268]
The `propagator` package correctly implements a necessary component in hooking user spans into GCP-generated traces. However, it is not mentioned in the README and not used in the examples. In fact, no code in the repo refers to it.

Please modify both the README and the example to use it.

**Comment by jba** [comment]
On a related note, maybe the recommended sampler should be different. https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/example/trace/http/server/server.go#L45 mentions a ProbabilitySampler, but that doesn't actually exist (at least as of go.opentelemetry.io/otel/sdk/trace v1.3.0). It seems to be replaced by TraceIDRatioBased. But also, if you want your spans to be children of the incoming one, then you probably want to sample iff the parent is sampled. So I would suggest
```
sdktrace.WithSampler(sdktrace.ParentBased(sdktrace.TraceIDRatioBased(SOME_FRACTION))
```
which will use the parent, and fall back to a fraction of traces if there is no parent.

**Comment by jsuereth** [comment]
There's actually an issue we've been trying to decide on the right way to solve, which has lead to us not advertising this propagator.


Specifically, the "sampled" flag in X-Cloud-Trace-Context has different meaning from w3c trace context.  

Specifically:

- [w3c trace context sampled flag means "mean have recorded trace data", and allows flexible downstream sampling](https://www.w3.org/TR/trace-context/#sampled-flag)
- [x-cloud-trace context sampled flag means "force collect trace data" or "do not sample"](https://cloud.google.com/trace/docs/setup#force-trace)

In practice, we've found that for some customers just attaching `traceparent <-> x-cloud-trace-context` leads to oversampling, which is why we don't advertise it right now.  

A few notes from your comments:

- `TraceIdRatioBased` is a probability sampler that assumes randomness in your trace_id.  OTel is looking to modify the w3c spec to require randomness for this to work w/ non-otel trace_ids.
- If we have OpenTelemetry *only attach* to w3c-trace-context incoming spans (and not set x-cloud-trace-context for downstream GCP services), then we shouldn't see the oversampling issue.
- If you *only* use OTel's parent-based + trace-id-ratio based samplers you likely won't see the issue (although I need to go verify a few assumptions there).

**Comment by ymotongpoo** [comment]
@punya sure! 

So here are couple of topics mentioned above:

1. Refer XCTC in README (update README)
2. Mapping of traceSampled flag between XCTC and W3C.

For 1, I can take it with the warnings that XCTC's flag is not 100% compat with W3C. If the action include 2., I would like to have a consensus on how we should map the flags between headers.

**Comment by jsuereth** [comment]
I'd suggest that the actual action item we should take (in the near term) is the following:

1. Document how to use XCTC propagator in the README with the following changes:
   - It will *only* attach to parent XCTC spans, but will not synthesize/send new XCTC for downstream requests (i.e. it reads, but doesn't write)
   - We're "ok" for the minor discrepency in the flag if we use the above scenario.
2. We'll likely need to create some kind of "vendor extension" for w3c tracestate that allows us to communicate meaning from XCTC properly if we want.   That's in our longer term path, as we should coordinate with how GCP creates traces + XCTC headers.

**Comment by muncus** [comment]
Is anyone actively working on this, and/or would you mind if I picked it up?

I'm happy to turn the existing `propagator` package into a one-way XCTC->traceparent. This would let OTel users have the same Trace ID as GCP, and make traces more valuable for interactions with GCP support.

Regarding the traceSampled flag discrepancy, I think a README paragraph offering the strategy @jsuereth mentioned to avoid the oversampling is the right short-term action. Users already control sampling on their own, and it never hurts to offer a recommended strategy, IMO.

**Comment by dashpole** [comment]
Thanks @muncus.  We can go ahead with the addition of the one-way propagator.  Let's make sure we don't break the current propagator package's public API, though.

As for documentation, we should:
1. Document the discrepancy between the two definitions of sampled in XCTC vs w3c
2. Recommend using the one-way over the two-way propagator, and make sure it is set first (?) in the composite propagator list in examples to ensure the W3C context takes precedence, if it exists.
3. Document the resulting difference in behavior when using one-way vs two way
