### ISSUE TITLE
Multi-project export uses quota from the credential's project.

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#411]
If you have a service account from project A, and override to send telemetry to project B using `gcp.project.id`, it will use quota from project A.  This probably isn't what users expect.

There is an [option](https://github.com/googleapis/google-api-go-client/blob/2bdb4a9808454c2e43c015b99011a42d084aa02d/internal/settings.go#L53) when we Dial the grpc client called QuotaProject we could use to override the project used for quota.

We need to decide what the best way to handle this is.

**Comment by aabmass** [comment]
@damemi taking a look

**Comment by damemi** [comment]
I don't think this is possible without a change to the cloud trace/monitoring/logging libraries, or possibly grpc (https://github.com/googleapis/google-api-go-client/issues/1780).

* the grpc QuotaProject option won't work because it is a DialOption, and we want to set this dynamically for each call
* the `x-goog-user-project` header could work, but this is always set by the underlying grpc libraries to be the default credential's project. 
* we don't have a way to override this and it appears like hardcoded behavior in the grpc libraries.
* in the future, we might be able to use a chained interceptor to override this

I'm going to follow the issue I created in grpc to see if I'm missing something obvious. Otherwise, we'll close this as out of our current scope and we can reopen it if needed.

**Comment by damemi** [comment]
Looking more into this it seems like running a collector without a default quota project defined in creds does work, so I opened https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/555
